# Set browser
export BROWSER="/mnt/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"

# Set display
export DISPLAY="$(/sbin/ip route | awk '/default/ { print $3 }'):0"

# Set path
if [ -d "$HOME/.bun/bin" ]; then
    export PATH="$HOME/.bun/bin:$PATH"
fi
if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# Set zsh history file
HISTFILE="${ZDOTDIR:-$HOME}/.zsh_history"
HISTTIMEFORMAT="[%F %T] "
HISTSIZE=1000000
SAVEHIST=100000

# Configure auto suggestions
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_COMPLETION_IGNORE="git *"
