# Set browser
export BROWSER=/mnt/c/Program\ Files\ (x86)/Microsoft/Edge/Application/msedge.exe

# Set display
export DISPLAY="$(/sbin/ip route | awk '/default/ { print $3 }'):0"

unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
  export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi
export GPG_TTY=$TTY
eval "$(gpg-connect-agent updatestartuptty /bye >/dev/null)"
#eval "$(keychain --quiet --agents gpg --eval 0x7E3F3C9C9599B027)"

# Set path
if [ -d "$HOME/.local/bin" ]; then
    export PATH="$HOME/.local/bin:$PATH"
fi

# Pyenv path
if [ -d $HOME/.penv ]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    source $PYENV_ROOT/zpyenv.path.zsh
fi

# Set zsh history file
HISTFILE="${ZDOTDIR:-$HOME}/.zsh_history"
HISTTIMEFORMAT="[%F %T] "
HISTSIZE=1000000
SAVEHIST=100000

# Configure auto suggestions
ZSH_AUTOSUGGEST_STRATEGY=(match_prev_cmd completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20
ZSH_AUTOSUGGEST_COMPLETION_IGNORE="git *"
