# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load ls_colors
source $HOME/.local/share/lscolors.sh

# Load options
source $ZDOTDIR/.options

# Load functions
source $ZDOTDIR/.functions

# Load aliases
source $ZDOTDIR/.aliases

### Added by Zinit's installer
if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
      zinit-zsh/z-a-rust \
      zinit-zsh/z-a-as-monitor \
      zinit-zsh/z-a-patch-dl \
      zinit-zsh/z-a-bin-gem-node

# Load theme and plugins without Turbo
zinit for \
      agkozak/zsh-z \
  light-mode depth"1" \
      romkatv/powerlevel10k

# Load a few useful plugins for zsh with Turbo
zinit wait lucid for \
  light-mode atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
      Aloxaf/fzf-tab \
  light-mode \
      zdharma/fast-syntax-highlighting \
  light-mode atload"_zsh_autosuggest_start" \
      zsh-users/zsh-autosuggestions \
  blockf atpull"zinit creinstall -q ." \
      zsh-users/zsh-completions

zinit wait"0b" lucid for \
      OMZP::colored-man-pages \
      OMZP::command-not-found

zinit wait"0c" lucid for \
      OMZL::git.zsh \
      OMZP::git \
      OMZP::pipenv

zinit as"null" wait"1" lucid \
  atclone'PYENV_ROOT="$PWD" ./libexec/pyenv init --path > zpyenv.zsh' \
  atinit'export PYENV_ROOT="$PWD"' atpull"%atclone" \
  atload'eval "$(pyenv init -)"' \
  sbin"bin/pyenv" src"zpyenv.zsh" nocompile'!' for \
      pyenv/pyenv

### End of Zinit's installer chunk


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
