# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load options
source $ZDOTDIR/.options

# Load functions
source $ZDOTDIR/.functions

# Load aliases
source $ZDOTDIR/.aliases

# Load Zi
source <(curl -sL https://git.io/zi-loader); zzinit

autoload -Uz _zi
(( ${+_comps} )) && _comps[zi]=_zi

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zi light-mode for \
    z-shell/z-a-meta-plugins \
    @annexes \
    @romkatv

# Load theme and plugins without Turbo
zi for \
    agkozak/zsh-z

# Load a few useful plugins for zsh with Turbo
zi wait lucid for \
    as"completion" \
        OMZP::docker/_docker \
    OMZP::colored-man-pages \
    OMZP::command-not-found \
    OMZP::sudo \
    OMZP::git \
    OMZL::git.zsh

zi wait"1a" lucid reset \
    atclone"[[ -z ${commands[dircolors]} ]] && local P=g
        \${P}sed -i '/DIR/c\DIR 38;5;63;1' LS_COLORS; \
        \${P}dircolors -b LS_COLORS > clrs.zsh" \
    atpull'%atclone' pick"clrs.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors "${(s.:.)LS_COLORS}"' for \
        trapd00r/LS_COLORS

zi wait"2a" lucid as"null" from"gh-r" for \
    sbin"bin/exa" \
        ogham/exa \
    sbin"fd/fd" \
        @sharkdp/fd

zi wait"2b" lucid for \
    light-mode \
        Aloxaf/fzf-tab \
    as"null" from"gh" atinit"export PYENV_ROOT='$HOME/.pyenv'" \
    atclone"PYENV_ROOT='$HOME/.pyenv' ./libexec/pyenv init - > zpyenv.zsh" \
    atpull"%atclone" src"zpyenv.zsh" nocompile"!" sbin"bin/pyenv" \
        pyenv/pyenv

zi wait lucid light-mode for \
    z-shell/H-S-MW \
    atinit"ZI[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
        z-shell/F-Sy-H \
    atload"_zsh_autosuggest_start" \
        zsh-users/zsh-autosuggestions \
    blockf atpull'zi creinstall -q .' \
        zsh-users/zsh-completions

# ### End of Zi's installer chunk

# Load colors
autoload -U colors
colors

autoload -U bashcompinit
bashcompinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
