# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Load options
source $ZDOTDIR/.options

# Load functions
source $ZDOTDIR/.functions

# Load aliases
source $ZDOTDIR/.aliases

## Added by Zinit's installer
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

if [[ ! -f "${ZINIT_HOME}/zinit.zsh" ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma-continuum/zinit%F{220})…%f"
    command mkdir -p "$(dirname $ZINIT_HOME)" && command chmod g-rwX "$(dirname $ZINIT_HOME)"
    command git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi

source "${ZINIT_HOME}/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

autoload -U bashcompinit
bashcompinit

# Load colors
autoload -U colors
colors

# Load a few important annexes, without Turbo
# (this is currently required for annexes)
zinit light-mode for \
    zdharma-continuum/zinit-annex-as-monitor \
    zdharma-continuum/zinit-annex-bin-gem-node \
    zdharma-continuum/zinit-annex-patch-dl \
    zdharma-continuum/zinit-annex-rust

# Load theme and plugins without Turbo
zinit for \
        agkozak/zsh-z \
    light-mode depth"1" \
        romkatv/powerlevel10k

# Load a few useful plugins for zsh with Turbo
zinit wait lucid for \
    OMZP::colored-man-pages \
    OMZP::command-not-found

zinit wait lucid for \
    OMZP::sudo \
    OMZP::git \
    OMZL::git.zsh

zinit wait lucid as"null" from"gh-r" for \
    sbin"bin/exa" \
        ogham/exa

zinit wait lucid reset \
    atclone"[[ -z ${commands[dircolors]} ]] && local P=g
        \${P}sed -i '/DIR/c\DIR 38;5;63;1' LS_COLORS; \
        \${P}dircolors -b LS_COLORS > clrs.zsh" \
    atpull'%atclone' pick"clrs.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors "${(s.:.)LS_COLORS}"' for \
        trapd00r/LS_COLORS

zinit wait"1a" lucid light-mode for \
    atinit"ZINIT[COMPINIT_OPTS]=-C; zicompinit; zicdreplay" \
        Aloxaf/fzf-tab

zinit wait"1" lucid for \
    light-mode \
        zdharma-continuum/fast-syntax-highlighting \
    blockf atpull"zinit creinstall -q ." \
        zsh-users/zsh-completions
    atload"!_zsh_autosuggest_start" \
        zsh-users/zsh-autosuggestions

### End of Zinit's installer chunk

# Pyenv install
if [ -d $PYENV_ROOT ]; then
    source $PYENV_ROOT/zpyenv.zsh
    source $PYENV_ROOT/zpyenv.venv.zsh
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
